<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;


class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Authorizable, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        "first_name",
        "sur_name",
        "mid_name",
        "birth_date",
        "ctzn",
        "per_adr",
        "tin",
        "gd",
        "natn",
        "_pport_issue_date",
        "_pport_expr_date",
        "pport_no",
        "pin",
        "birth_place",
        "valid",
        "user_type",
        "ret_cd",
        "legal_info",
        "legal_tin",
        "type",
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function roles()
    {
        return $this
            ->belongsToMany('App\Role')
            ->withTimestamps();
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
    public function services()
    {
        return $this->hasMany(Service::class);
    }
    public function isAdmin(){
        if ($this->role===2) return true;
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        /*static::saving(function($user){

            $date1= new \Carbon\Carbon($user->_pport_issue_date);
            $odate1= new \Carbon\Carbon($user->_pport_issue_date);
            $date2=new \Carbon\Carbon($user->_pport_expr_date);
            $odate2=new \Carbon\Carbon($user->_pport_expr_date);
            if($date1->subDay()->getTimestamp() !== $date2->subYears(10)->getTimestamp()){
                $user->_pport_issue_date=$odate1->year  . "-" . $odate1->day < 10 ? '0'. $odate1->day:$odate1->day . "-" . ($odate1->month < 10 ? '0'.$odate1->month:$odate1->month);
                $user->_pport_expr_date=$odate2->year  . "-" . $odate2->day < 10 ? '0'. $odate2->day:$odate2->day . "-" . ($odate2->month < 10 ? '0'.$odate2->month:$odate2->month);
                dd($user);
                $user->save();
            }


        });*/
    }


}
